#!/usr/bin/env python3
# Copyright (c) 2015 - 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

"""Sanitized replays of rocAL's golden-image scripts, and their classification.

rocAL ships two golden sweeps that must never be run as-is: unit_tests/testAllScripts.sh
(``sudo rm -rf ./build/*`` plus an in-place build) and python_api/unit_tests.sh (writes
into its CWD). This module rewrites them into drivers that replay the exact upstream
./unit_tests / python3.X lines in upstream order, and then classifies every call.

    ut_sweep.py sanitize --kind cpp|py --src SCRIPT --out DRIVER --out-dir DIR
    ut_sweep.py classify-cpp --runs DIR... --out-dir DIR --golden DIR --comparator-log F
    ut_sweep.py classify-py  --runs DIR... --out-dir DIR --comparator-log F
    ut_sweep.py blocked --kind cpp|py --runs DIR... --reason TEXT

The drivers call ``./unit_tests`` (a recording wrapper in the run directory) or a
``python3.12`` shell function injected into the script. Each call appends a JSON line
to ``<run>/calls.jsonl``: ``{n, rc, dur, log, snap, args}``. With VP_UT_DRY=1 the
wrappers only record the arguments, which gives the expected call list.

Upstream-rule classification (``golden-cpp.<host|hip>.<gray|rgb>``, ``golden-py.<cpu|gpu>.<gray|rgb>``):
  exit 255 + "Not a valid option" (Python: exit 0 + that text)  -> skip
  timeout / signal                                            -> error
  other non-zero exit                                         -> fail
  exit 0 without an output file                               -> fail
  random augmentation or Log (upstream never compares them)   -> skip ("unchecked")
  output name reused by a later call (upstream compares the last one only) -> skip
  no golden image                                             -> skip
  comparator PASSED / FAILED                                  -> pass / fail
  comparator stopped before the case (no totals line)         -> error
The C++ sweep also gets a stricter analysis (``golden-cpp-strict.*``, see strict_cpp()).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(os.environ.get("VP_REPO", Path(__file__).resolve().parents[2])) / "build_tools" / "results"))
from emit import append_record  # noqa: E402

SUITE = "rocal"
RANDOM_AUGS = ["Snow", "Rain", "Jitter", "SNPNoise", "Fog", "GaussianNoise", "ShotNoise", "Spatter"]
# unit_tests.cpp reader_type values, as ID-safe names (used to disambiguate reused output names).
CPP_READERS = {0: "file", 1: "file_partial", 2: "coco", 3: "coco_partial", 4: "tf_cls", 5: "tf_det", 6: "caffe_cls",
               7: "caffe_det", 8: "caffe2_cls", 9: "caffe2_det", 10: "coco_kp", 11: "mxnet", 12: "webdataset",
               13: "numpy", 14: "file_partial_ss", 15: "coco_iou_ss", 16: "coco_partial_ss", 17: "caffe_cls_ss",
               18: "caffe2_cls_ss", 19: "mxnet_ss", 20: "numpy_ss", 21: "file_ss", 22: "caffe_partial_ss",
               23: "caffe2_partial_ss", 24: "tf_cls_ss", 25: "webdataset_idx", 26: "coco_boxenc_ss", 27: "tf_raw",
               28: "tf_raw_ss"}
FORBIDDEN = re.compile(r"(^|[\s;&|(`])(sudo|rm|rmdir|make|cmake|git|shutil|chmod|chown|cd)(\s|$)")


# ---------------------------------------------------------------------------
# sanitizer
# ---------------------------------------------------------------------------

CPP_WRAPPER = r'''#!/usr/bin/env bash
# Recording stand-in for ./unit_tests (generated by suites/rocal/ut_sweep.py).
set -u
d="${VP_UT_DIR:?}"
n=$(( $(cat "${d}/.counter" 2>/dev/null || echo 0) + 1 ))
echo "${n}" >"${d}/.counter"
args="$(printf '%s\0' "$@" | jq -cRs 'split("\u0000")[:-1]')"
if [[ "${VP_UT_DRY:-0}" == 1 ]]; then
  jq -cn --argjson n "${n}" --argjson args "${args}" '{n:$n, args:$args}' >>"${d}/calls.jsonl"
  exit 0
fi
log="${d}/logs/$(printf %04d "${n}").log"
png="${3:-none}.png"
marker="${d}/.marker"
: >"${marker}"
t0="$(date +%s.%N)"
timeout -k 10 "${VP_UT_TIMEOUT:-300}" "${VP_UT_BIN:?}" "$@" >"${log}" 2>&1
rc=$?
t1="$(date +%s.%N)"
snap=""
if [[ -f "${png}" && -n "$(find "${png}" -newer "${marker}" 2>/dev/null)" ]]; then
  snap="${d}/snap/$(printf %04d "${n}").png"
  cp "${png}" "${snap}"
fi
jq -cn --argjson n "${n}" --argjson rc "${rc}" --arg t0 "${t0}" --arg t1 "${t1}" --arg log "${log}" --arg snap "${snap}" \
  --argjson args "${args}" '{n:$n, rc:$rc, dur:(($t1|tonumber)-($t0|tonumber)), log:$log, snap:$snap, args:$args}' \
  >>"${d}/calls.jsonl"
exit "${rc}"
'''

PY_WRAPPER = r'''
# Recording stand-in for python3.X (generated by suites/rocal/ut_sweep.py).
python3.12() {
  local d="${VP_UT_DIR:?}" n log marker out t0 t1 rc snap a prev="" args
  n=$(( $(cat "${d}/.counter" 2>/dev/null || echo 0) + 1 ))
  echo "${n}" >"${d}/.counter"
  args="$(printf '%s\0' "$@" | jq -cRs 'split("\u0000")[:-1]')"
  if [[ "${VP_UT_DRY:-0}" == 1 ]]; then
    jq -cn --argjson n "${n}" --argjson args "${args}" '{n:$n, args:$args}' >>"${d}/calls.jsonl"
    return 0
  fi
  out=""
  for a in "$@"; do [[ "${prev}" == "-f" ]] && out="${a}"; prev="${a}"; done
  log="${d}/logs/$(printf %04d "${n}").log"
  marker="${d}/.marker"
  : >"${marker}"
  t0="$(date +%s.%N)"
  timeout -k 10 "${VP_UT_TIMEOUT:-300}" "${VP_UT_PY:?}" "$@" >"${log}" 2>&1
  rc=$?
  t1="$(date +%s.%N)"
  snap=""
  for a in "${out}.png" "${out}"; do
    if [[ -n "${out}" && -f "${a}" && -n "$(find "${a}" -newer "${marker}" 2>/dev/null)" ]]; then
      snap="${d}/snap/$(printf %04d "${n}")_$(basename "${a}")"
      cp "${a}" "${snap}"
      break
    fi
  done
  jq -cn --argjson n "${n}" --argjson rc "${rc}" --arg t0 "${t0}" --arg t1 "${t1}" --arg log "${log}" --arg snap "${snap}" \
    --argjson args "${args}" '{n:$n, rc:$rc, dur:(($t1|tonumber)-($t0|tonumber)), log:$log, snap:$snap, args:$args}' \
    >>"${d}/calls.jsonl"
  return "${rc}"
}
'''


def sanitize(kind: str, src: str, out: str, out_dir: str) -> int:
    lines = Path(src).read_text().splitlines()
    start = next((i for i, ln in enumerate(lines) if re.match(r'\s*if \[\[ \$ROCAL_DATA_PATH == ""', ln)), None)
    if start is None:
        print(f"sanitize: no ROCAL_DATA_PATH check in {src}; refusing to guess where the build block ends")
        return 2
    body = ["#!/usr/bin/env bash", f"# Sanitized replay of {src} (generated by suites/rocal/ut_sweep.py)."]
    if kind == "py":
        body.append(PY_WRAPPER)
    n_calls = 0
    for ln in lines[start:]:
        s = ln.strip()
        if s.startswith("output_path="):
            ln = f'output_path="{out_dir.rstrip("/")}/"'
        elif s.startswith('mkdir "$output_path"'):
            ln = 'mkdir -p "$output_path"'
        elif "image_comparison.py" in s:
            continue  # the suite runs the comparator itself, in a scratch CWD
        elif s.startswith("ver=$(python3"):
            ln = "ver=3.12"
        # LMDB readers rewrite lock.mdb (M14): point them at the private copies.
        ln = ln.replace("${ROCAL_DATA_PATH}/rocal_data/caffe", "${VP_UT_LMDB:?}/caffe")
        code = ln.split("#", 1)[0]
        if FORBIDDEN.search(code):
            print(f"sanitize: refusing to run a line with a forbidden command: {ln.strip()}")
            return 3
        if re.search(r"\./unit_tests\b|python\"\$ver\"", code):
            n_calls += 1
        body.append(ln)
    if any("rocal_data/caffe" in ln for ln in body):
        print("sanitize: a Caffe/Caffe2 path still points at the shared dataset")
        return 4
    if n_calls == 0:
        print("sanitize: no test calls found")
        return 5
    Path(out).write_text("\n".join(body) + "\n")
    print(f"sanitized {src}: {n_calls} call lines -> {out}")
    return 0


def write_wrapper(run_dir: str) -> None:
    d = Path(run_dir)
    for sub in ("logs", "snap"):
        (d / sub).mkdir(parents=True, exist_ok=True)
    w = d / "unit_tests"
    w.write_text(CPP_WRAPPER)
    w.chmod(0o755)


# ---------------------------------------------------------------------------
# call records
# ---------------------------------------------------------------------------

def load_calls(run_dir: str) -> list[dict]:
    p = Path(run_dir) / "calls.jsonl"
    if not p.exists():
        return []
    return [json.loads(ln) for ln in p.read_text().splitlines() if ln.strip()]


def golden_name(base: str) -> tuple[str, list[str]]:
    parts = base.split(".")[0].split("_")
    if len(parts) > 3:
        return "_".join(parts[:-1]) + ".png", parts[:-1]
    return base + ".png", parts


def is_unchecked_cpp(parts: list[str]) -> bool:
    return parts[0] in RANDOM_AUGS or "Random" in parts[0] or "Log" in parts[0]


def cpp_case(args: list[str]) -> dict:
    out = args[2]
    return {"reader": int(args[0]), "out": out, "base": os.path.basename(out), "aug": int(args[5]),
            "dev": "hip" if args[6] == "1" else "host", "color": "rgb" if args[7] == "1" else "gray",
            "tail": args[10:]}


def py_case(args: list[str]) -> dict:
    def opt(name, default=""):
        return args[args.index(name) + 1] if name in args and args.index(name) + 1 < len(args) else default
    out = opt("-f")
    return {"reader": opt("--reader-type", "file"), "out": out, "base": os.path.basename(out),
            "aug": opt("--augmentation-name"), "dev": "gpu" if "--rocal-gpu" in args else "cpu",
            "color": "rgb" if opt("--color-format", "1") == "1" else "gray",
            "tail": [a for a in args if a.startswith("--interpolation") or a.startswith("--scaling")]}


def tail_name(tail: list[str]) -> str:
    """unit_tests' optional trailing arguments, named (interp, scaling, memcpy, layout, reverse)."""
    if len(tail) >= 5 and all(t.isdigit() for t in tail[:5]):
        return f"mem{tail[2]}-{'nchw' if tail[3] == '1' else 'nhwc'}-rev{tail[4]}"
    return "-".join(t.lstrip("-") for t in tail)


def assign_ids(cases: list[dict], reader_name) -> None:
    """Case name = output basename; names reused within a device/colour pair get a stable suffix."""
    groups = defaultdict(list)
    for c in cases:
        groups[(c["dev"], c["color"], c["base"])].append(c)
    for members in groups.values():
        if len(members) == 1:
            members[0]["name"] = members[0]["base"]
            continue
        keys = [(reader_name(m["reader"]), f"aug{m['aug']}", tail_name(m["tail"])) for m in members]
        differing = [i for i in range(3) if len({k[i] for k in keys}) > 1]
        seen = Counter()
        for m, k in zip(members, keys, strict=True):
            suffix = ".".join(k[i] for i in differing if k[i])
            name = f"{m['base']}~{suffix}" if suffix else m["base"]
            seen[name] += 1
            m["name"] = name if seen[name] == 1 else f"{name}#{seen[name]}"


def expected_and_observed(runs: list[str], parse) -> list[dict]:
    """Join the dry-run call list (expected) with the recorded calls of each run directory."""
    cases = []
    for run in runs:
        dry = load_calls(os.path.join(run, "dry"))
        real = {c["n"]: c for c in load_calls(run)}
        for exp in dry:
            c = parse(exp["args"])
            c["call"] = real.get(exp["n"])
            if c["call"] and c["call"]["args"] != exp["args"]:
                c["call"] = None
                c["mismatch"] = True
            cases.append(c)
    return cases


def read_log(call: dict | None, limit: int = 200_000) -> str:
    if not call or not call.get("log"):
        return ""
    try:
        return Path(call["log"]).read_text(errors="replace")[-limit:]
    except OSError:
        return ""


def tail_msg(txt: str, n: int = 4) -> str:
    lines = [ln for ln in txt.splitlines() if ln.strip() and not ln.startswith("OK:")]
    return " | ".join(lines[-n:])[:1500]


def rel(p: str) -> str:
    out = os.environ.get("VP_OUT", "")
    return p[len(out) + 1:] if out and p.startswith(out + "/") else p


# ---------------------------------------------------------------------------
# upstream comparator log
# ---------------------------------------------------------------------------

def parse_comparator(path: str) -> tuple[dict, tuple[int, int] | None, str]:
    verdicts: dict[str, dict] = {}
    totals = None
    current = None
    size_exit = ""
    try:
        text = Path(path).read_text(errors="replace")
    except OSError:
        return verdicts, None, "no comparator log"
    for ln in text.splitlines():
        m = re.search(r"Running (\S+)", ln)
        if m:
            current = m.group(1)
            verdicts[current] = {"verdict": "RUNNING", "detail": []}
            continue
        if current and re.search(r"INFO:root:PASSED", ln):
            verdicts[current]["verdict"] = "PASSED"
        elif current and re.search(r"INFO:root:FAILED", ln):
            verdicts[current]["verdict"] = "FAILED"
        elif current and ("pixel mismatch" in ln or "Mismatach percentage" in ln or "total mismatches" in ln):
            verdicts[current]["detail"].append(ln.split("INFO:root:", 1)[-1].strip())
        elif "different sizes" in ln and current:
            verdicts[current]["verdict"] = "SIZE_EXIT"
            size_exit = current
        m = re.search(r"Total case passed --> (\d+) / (\d+)", ln)
        if m:
            totals = (int(m.group(1)), int(m.group(2)))
    note = f"comparator exited early on a size mismatch at {size_exit}" if size_exit else ""
    return verdicts, totals, note


def comparator_record(group: str, path: str, rc: int) -> None:
    verdicts, totals, note = parse_comparator(path)
    failed = sorted(k for k, v in verdicts.items() if v["verdict"] in ("FAILED", "SIZE_EXIT"))
    if totals is None:
        status, msg = "error", f"no 'Total case passed' line (comparator rc {rc}); {note}".strip("; ")
    else:
        status = "fail" if failed else "pass"
        msg = f"Total case passed --> {totals[0]} / {totals[1]}; comparator rc {rc} (it always exits 0)"
        if failed:
            msg += f"; failing: {', '.join(failed)}"
    append_record(os.environ["VP_RESULTS"], SUITE, f"{group}::upstream-comparator", status, message=msg,
                  log=rel(path))


# ---------------------------------------------------------------------------
# strict pixel analysis (port of the manual session's analyze.py)
# ---------------------------------------------------------------------------

def _load(path: str):
    import numpy as np
    from PIL import Image
    img = Image.open(path)
    sample = img.getpixel((0, 0))
    return (np.asarray(img.convert("RGB")) if isinstance(sample, tuple) else np.asarray(img.convert("L"))), img.size


def compare_png(ref: str, out: str, name: str) -> dict:
    """Same pass criteria as upstream image_comparison.py, without its early exit on a size mismatch."""
    import numpy as np
    ra, sa = _load(ref)
    rb, sb = _load(out)
    if sa != sb:
        return {"verdict": "FAIL_SIZE", "detail": f"size {sb} vs golden {sa}"}
    if ra.ndim != rb.ndim:
        ra = ra.mean(axis=2).astype(np.uint8) if ra.ndim == 3 else ra
        rb = rb.mean(axis=2).astype(np.uint8) if rb.ndim == 3 else rb
    if "larger" in name or "smaller" in name:
        second = 400 if "larger" in name else 2400
        rows = list(range(0, 400)) + list(range(second, second + 400))
        ra, rb = ra[rows][:, :400], rb[rows][:, :400]
    d = np.minimum(np.abs(ra.astype(np.int16) - rb.astype(np.int16)), 5)
    hist = [int((d == k).sum()) for k in range(6)]
    mism = sum(hist[1:])
    pct = round(mism / max(d.size, 1) * 100, 2)
    ok = (mism == 0 or (pct < 5.0 and hist[1] == mism)
          or (pct < 0.5 and ("Blend" in name or "Rotate" in name) and "hip" in name)
          or (pct < 0.5 and "JpegCompressionDistortion" in name))
    return {"verdict": "PASS" if ok else "FAIL", "detail": f"mismatch {pct}% hist={hist}"}


def degenerate(path: str) -> bool:
    a, _ = _load(path)
    return int(a.min()) == int(a.max())


def parity(a_path: str, b_path: str) -> tuple[bool, str]:
    import numpy as np
    a, sa = _load(a_path)
    b, sb = _load(b_path)
    if sa != sb or a.shape != b.shape:
        return False, f"host {sa} vs hip {sb} differ in size"
    d = np.abs(a.astype(np.int16) - b.astype(np.int16))
    pct = float((d > 1).mean() * 100)
    return pct <= 5.0, f"host vs hip: {pct:.2f}% of values differ by more than 1 (max {int(d.max())})"


# ---------------------------------------------------------------------------
# classification
# ---------------------------------------------------------------------------

def run_status(c: dict, kind: str) -> tuple[str, str] | None:
    """Status decided by the call itself (before any pixel comparison), or None to continue."""
    call = c["call"]
    if call is None:
        return "error", ("argument mismatch against the dry run" if c.get("mismatch")
                         else "not executed (the driver stopped before this call)")
    rc, txt = call["rc"], read_log(call)
    if kind == "cpp" and rc == 255 and "Not a valid option" in txt:
        return "skip", "not applicable: unit_tests rejects this reader/augmentation/colour combination"
    if kind == "py" and rc == 0 and "Not a valid option" in txt:
        return "skip", "not applicable: unit_test.py rejects this augmentation for greyscale"
    if kind == "py" and rc == 0 and "Install tensorflow" in txt:
        return "blocked", "tensorflow is not installed: the TF reader printed 'Install tensorflow' and exited 0"
    if rc in (124, 137):
        return "error", f"timeout (rc {rc}); {tail_msg(txt)}"
    if rc > 128 or rc < 0:
        sig = rc - 128 if rc > 128 else -rc
        return "error", f"killed by signal {sig} (rc {rc}); {tail_msg(txt)}"
    if rc != 0:
        return "fail", f"exit {rc}; {tail_msg(txt)}"
    if kind == "py" and "Verify graph failed" in txt:
        return "fail", "Pipeline.build() printed 'Verify graph failed' and exited 0 (M8); " + tail_msg(txt)
    if kind == "py" and "SUCCESS" not in txt:
        return "fail", "exit 0 without the SUCCESS banner; " + tail_msg(txt)
    if not call.get("snap"):
        return "fail", "exit 0 but no output file was written; " + tail_msg(txt)
    return None


def last_writers(cases: list[dict]) -> dict[str, dict]:
    """Output path -> the case whose file upstream's comparator actually sees (the last successful writer)."""
    last = {}
    for c in cases:
        if c["call"] and c["call"].get("snap"):
            last[c["out"]] = c
    return last


def classify(kind: str, runs: list[str], golden: str, comparator_log: str) -> int:
    results = os.environ["VP_RESULTS"]
    parse, readers = (cpp_case, lambda r: CPP_READERS.get(r, f"r{r}")) if kind == "cpp" else (py_case, str)
    cases = expected_and_observed(runs, parse)
    assign_ids(cases, readers)
    verdicts, totals, cmp_note = parse_comparator(comparator_log)
    golden_files = set(os.listdir(golden)) if golden and os.path.isdir(golden) else set()
    last = last_writers(cases)
    group_prefix = "golden-cpp" if kind == "cpp" else "golden-py"
    counts = Counter()
    for c in cases:
        cid = f"{group_prefix}.{c['dev']}.{c['color']}::{c['name']}"
        call = c["call"] or {}
        gname, parts = golden_name(c["base"])
        st = run_status(c, kind)
        if st is None:
            unchecked = is_unchecked_cpp(parts) if kind == "cpp" else parts[0] in RANDOM_AUGS
            onehot = kind == "py" and parts[0] == "OneHot"
            v = verdicts.get(c["base"])
            if unchecked:
                st = ("skip", "unchecked: upstream auto-passes random augmentations"
                      + (" and Log" if kind == "cpp" else "") + "; ran with exit 0 and wrote its output")
            elif last.get(c["out"]) is not c:
                st = ("skip", "not compared: a later call reuses this output name, so upstream only compares "
                      f"the last writer ({last[c['out']]['name']})")
            elif not onehot and gname not in golden_files:
                st = ("skip", f"no golden image {gname}")
            elif v is None:
                st = ("error", "the upstream comparator did not report this case"
                      + ("" if totals else f" (no totals line: {cmp_note or 'it stopped early'})"))
            elif v["verdict"] == "PASSED":
                st = ("pass", f"matches {gname if not onehot else 'the one-hot reference'}")
            elif v["verdict"] == "SIZE_EXIT":
                st = ("fail", f"output size differs from {gname}; the upstream comparator exited here")
            elif v["verdict"] == "FAILED":
                st = ("fail", f"differs from {gname}: " + "; ".join(v["detail"])[:1500])
            else:
                st = ("error", "comparator started this case but printed no verdict")
        counts[st[0]] += 1
        note = os.environ.get("VP_UT_NOTE", "")
        append_record(results, SUITE, cid, st[0], duration_s=call.get("dur", 0.0),
                      message=st[1] + (f" [{note}]" if note else ""),
                      log=rel(call.get("log", "")), backend="GPU" if c["dev"] in ("hip", "gpu") else "CPU",
                      repro=" ".join(call.get("args", [])))
    print(f"{group_prefix}: {len(cases)} calls classified: {dict(counts)}")
    if kind == "cpp":
        strict_cpp(cases, golden, golden_files, last)
    return 0


def strict_cpp(cases: list[dict], golden: str, golden_files: set, last: dict) -> None:
    """Stricter C++ analysis, per call on its own snapshot (golden-cpp-strict.*).

    - compared cases: upstream's pass criteria, but no early exit, and calls that reuse an
      output name with the same reader/augmentation (e.g. the 8 Copy layouts) are all compared;
    - random, Log and golden-less cases are not auto-passed: a blank (single-value) output
      fails, and deterministic ones (Log and golden-less non-random cases) must agree between
      host and hip (this is what exposes H8: GPU Log is all zeros, CPU Log is garbage).
    """
    results = os.environ["VP_RESULTS"]
    by_id = {(c["dev"], c["color"], c["name"]): c for c in cases}
    counts = Counter()
    for c in cases:
        cid = f"golden-cpp-strict.{c['dev']}.{c['color']}::{c['name']}"
        call = c["call"] or {}
        gname, parts = golden_name(c["base"])
        st = run_status(c, "cpp")
        if st is None:
            snap = call["snap"]
            lw = last.get(c["out"])
            same_source = lw is c or (lw is not None and lw["reader"] == c["reader"] and lw["aug"] == c["aug"])
            deterministic = "Log" in parts[0] or not (parts[0] in RANDOM_AUGS or "Random" in parts[0])
            if not is_unchecked_cpp(parts) and gname in golden_files and same_source:
                r = compare_png(os.path.join(golden, gname), snap, c["base"])
                st = ("pass", f"matches {gname}") if r["verdict"] == "PASS" else ("fail", f"vs {gname}: {r['detail']}")
            elif not same_source and gname in golden_files and not is_unchecked_cpp(parts):
                st = ("skip", f"golden {gname} belongs to a later call with another reader ({lw['name']})")
            elif degenerate(snap):
                st = ("fail", "output image is blank (every pixel has the same value)")
            elif deterministic and c["dev"] == "hip":
                host = by_id.get(("host", c["color"], c["name"].replace("_hip", "_host", 1)))
                hsnap = host and host["call"] and host["call"].get("snap")
                if hsnap:
                    ok, msg = parity(hsnap, snap)
                    st = ("pass", f"no golden; {msg}") if ok else ("fail", f"no golden; CPU and GPU disagree: {msg}")
                else:
                    st = ("skip", "no golden and no host output to compare with")
            else:
                why = "random augmentation" if not deterministic else "no golden (checked against hip on the hip side)"
                st = ("skip", f"{why}; output is non-blank")
        counts[st[0]] += 1
        append_record(results, SUITE, cid, st[0], duration_s=0.0, message=st[1], log=rel(call.get("log", "")),
                      backend="GPU" if c["dev"] == "hip" else "CPU")
    print(f"golden-cpp-strict: {len(cases)} calls: {dict(counts)}")


def blocked(kind: str, runs: list[str], reason: str, strict: bool) -> int:
    parse, readers = (cpp_case, lambda r: CPP_READERS.get(r, f"r{r}")) if kind == "cpp" else (py_case, str)
    cases = []
    for run in runs:
        cases += [parse(e["args"]) for e in load_calls(os.path.join(run, "dry"))]
    assign_ids(cases, readers)
    prefixes = (["golden-cpp"] + (["golden-cpp-strict"] if strict else [])) if kind == "cpp" else ["golden-py"]
    for p in prefixes:
        for c in cases:
            append_record(os.environ["VP_RESULTS"], SUITE, f"{p}.{c['dev']}.{c['color']}::{c['name']}", "blocked",
                          message=reason)
    print(f"{kind}: recorded {len(cases)} blocked cases per group")
    return 0 if cases else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("sanitize")
    p.add_argument("--kind", choices=["cpp", "py"], required=True)
    p.add_argument("--src", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--out-dir", required=True)
    p = sub.add_parser("wrapper")
    p.add_argument("run_dir", nargs="+")
    for name in ("classify-cpp", "classify-py"):
        p = sub.add_parser(name)
        p.add_argument("--runs", nargs="+", required=True)
        p.add_argument("--golden", default="")
        p.add_argument("--comparator-log", required=True)
        p.add_argument("--comparator-rc", type=int, default=0)
    p = sub.add_parser("blocked")
    p.add_argument("--kind", choices=["cpp", "py"], required=True)
    p.add_argument("--runs", nargs="+", required=True)
    p.add_argument("--reason", required=True)
    p.add_argument("--strict", action="store_true")
    a = ap.parse_args()
    if a.cmd == "sanitize":
        return sanitize(a.kind, a.src, a.out, a.out_dir)
    if a.cmd == "wrapper":
        for d in a.run_dir:
            write_wrapper(d)
        return 0
    if a.cmd in ("classify-cpp", "classify-py"):
        kind = a.cmd.split("-")[1]
        comparator_record("golden-cpp" if kind == "cpp" else "golden-py", a.comparator_log, a.comparator_rc)
        return classify(kind, a.runs, a.golden, a.comparator_log)
    return blocked(a.kind, a.runs, a.reason, a.strict)


if __name__ == "__main__":
    sys.exit(main())
